name: Chainlink Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm ci

      - name: Set up Environment Variables
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          echo "$PASSWORD" | npx env-enc set-pw
          echo "$PASSWORD" | npx env-enc set

      - name: Decrypt Environment Variables
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          echo "$PASSWORD" | npx env-enc view > .env

      - name: Deploy and Verify Contracts
        run: npm run deploy -- --network mumbai --verify true

      - name: Create, Fund, and Authorize Subscription
        run: npm run create-sub -- --network mumbai --amount <LINK_funding_amount> --contract <deployed_client_contract_address>

      - name: Transfer Tokens
        # TODO: Add step to transfer tokens (e.g., using MetaMask)

      - name: Resend On-Chain Requests
        run: npm run resend-requests -- --network mumbai --contract <deployed_client_contract_address> --subid <subscription_id>

      - name: Check Client Balance
        # TODO: Add step to verify client balance

      - name: Complete Deployment
        run: echo "Deployment completed"
