name: Chainlink Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

          
      - name: Deploy and Verify Contracts
        id: deploy
        run: npm run deploy -- --network mumbai --verify true
        env:
          CONTRACT_ADDRESS: ${{ steps.deploy.outputs.contract_address }}

      - name: Create, Fund, and Authorize Subscription
        run: npm run create-sub -- --network mumbai --amount ${{ env.LINK_FUNDING_AMOUNT }} --contract ${{ env.CONTRACT_ADDRESS }}

      - name: Transfer Tokens
        # TODO: Add step to transfer tokens (e.g., using MetaMask)

      - name: Resend On-Chain Requests
        run: npm run resend-requests -- --network mumbai --contract ${{ env.CONTRACT_ADDRESS }} --subid ${{ env.SUBSCRIPTION_ID }}


      - name: Complete Deployment
        run: echo "Deployment completed"
